name: Build Docker image and push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Build project (if needed)
        run: bash deb.sh
      # ---------------- DOCKER LOGIN ----------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # ---------------- BUILD IMAGE (TIMESTAMP TAG) ----------------
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/a:latest
      # ---------------- COMMIT RESULTS ----------------
      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add "GitHub Actions/"
          git commit -m "CI build + Trivy scan ${{ steps.timestamp.outputs.TIMESTAMP }}" || echo "No changes"
          git push origin master
